### ISSUE TITLE
Supporting inserts and deletes

### ISSUE THREAD

**Issue by jackwaudby** [jackwaudby/spaghetti#82]
Current design: 
- A`Database` is a `IntMap` of `Table`s
- `Table` is a `IntMap` of `Column`s
- `Column` is a `Vec` of `Tuple`s

**Comment by jackwaudby** [comment]
https://probablydance.com/2018/06/16/fibonacci-hashing-the-optimization-that-the-world-forgot-or-a-better-alternative-to-integer-modulo/

**Comment by jackwaudby** [comment]
https://docs.rs/nohash-hasher/0.2.0/nohash_hasher/type.IntMap.html

**Comment by jackwaudby** [comment]
Benchmarking crate: https://github.com/bheisler/criterion.rs

**Comment by iaindixon** [comment]
Run a benchmark test checking if the default "array" datastructure vs "intmap"

**Comment by jackwaudby** [comment]
### Design
`Database` is a enum with a variant for each workload containing a specific struct for that workload, e.g., `Database::Tatp(TatpDatabase)`. The workload struct then contains a fixed sized array of `Tables`, e.g., `TatpDatabase([Table; 4])`. A `Table` contains:
1. `IntMap<usize,Column>`; a `Column` is a fixed sized `Vec<Tuple>` acting as the primary data store.
2. `Mutex<BitVec>`; a bitmap indicating if the record at corresponding offset is in use.
3. `HashMap<PrimaryKey, usize>`; acts as an index for determining is a record with PrimaryKey exists in the database and at what offset, 
4. `Vec<AtomicU64>`; an atomic integer that is used to control access to records in some protocols.
5. `Vec<AtomicLinkedList<Access>>`; an atomic list per record that records accesses for use in some protocols.
Note, all fields (except the index) are pre-allocated to a size that will need be exceeded.  Additionally, the `HashMap` must be a concurrent data structure (see `flurry` crate).

### Insert
```
insert record X with key K into table T;
(i) lock T.bitmap
(ii) if K exists in T.index then abort
(iii) if no free offset in T.bitmap then abort; else get first free offset
(iv) for each value in record; set value in column
(v) set T.bitmap(offset)=T
(vi) insert (K,offset) into index
(vii) unlock T.bitmap
```

### Delete
```
delete record X with key K into table T;
(i) lock T.bitmap -- prevents concurrent deletions 
(ii) set X.deleted=T -- protocol dependent 
(iii) remove from index 
(iv) set T.bitmap(offset)=F
```

### Questions
- When do inserts/deletes become visible? 
- How to handle aborts? 

### Performance
Benchmark: `nocc`, 4 cores, 10K txns;
- `tatp-update-only` with `FxHashMap`: `94130.904 commit/s`
- `tatp-update-only` with  `flurry::HashMap`: `58900.103 commit/s`

**Comment by jackwaudby** [comment]
Leaving as static for now.
